### ISSUE TITLE
Teeny tiny bug (I love your mod!)

### ISSUE THREAD

**Issue by 851815** [sse2/gd-music-manager#1]
I love it! Just letting you know song volume behaves as if you exited the menu for the first time (whenever you go to the main menu from other screens)

https://github.com/sse2/gd-music-manager/assets/157591692/830e2560-9a64-4095-8ea4-dd49714cfad1

video should explain it (uploading here because I can't find who you are in the geode discord, uploaded to the #help channel)

**Comment by sse2** [comment]
Fixed in latest update
